### ISSUE TITLE
How this definition of "expression_pass1" works

### ISSUE THREAD

**Issue by mingodad** [vovkos/jancy#6]
I was looking again to create an alternative parser for `jancy` and following the `*.llk` files I found this definition of `expression_pass1`:
```
expression_pass1
	:	catch(eof) expression_pass1_item<&$.m_tokenList>+
	;

expression_pass1_item<sl::BoxList<Token>* $tokenList>
	:	'{'
			{
				$tokenList->insertTail($1);
			}
		expression_pass1_item<$tokenList>*
		'}'
			{
				$tokenList->insertTail($3);
			}
	|	'['
			{
				$tokenList->insertTail($1);
			}
		expression_pass1_item<$tokenList>*
		']'
			{
				$tokenList->insertTail($3);
			}
	|	'('
			{
				$tokenList->insertTail($1);
			}
		expression_pass1_item<$tokenList>*
		')'
			{
				$tokenList->insertTail($3);
			}
	|	any
			{
				$tokenList->insertTail($1);
			}
	;
```
And while trying to parse this:
```
	enum SizePolicy
	{
		Fixed = 0,
		Minimum = SizePolicyFlag.Grow,
		Maximum = SizePolicyFlag.Shrink,
		Preferred = SizePolicyFlag.Grow | SizePolicyFlag.Shrink,
		MinimumExpanding = SizePolicyFlag.Grow | SizePolicyFlag.Expand,
		Expanding = SizePolicyFlag.Grow| SizePolicyFlag.Shrink | SizePolicyFlag.Expand,
		Ignored = SizePolicyFlag.Shrink | SizePolicyFlag.Grow | SizePolicyFlag.Ignore
	}
```
How the `any` works to parse anything after `=` ?
Because the enum body definition is:
```
enum_block<EnumType* $type>
	:	(		{
					m_module->m_namespaceMgr.openNamespace($type);
					$type->m_namespaceStatus = NamespaceStatus_Ready;
				}
			'{' enum_const_list '}'
				{
					m_module->m_namespaceMgr.closeNamespace();
				}
		|	TokenKind_Body
				{
					setBody($type, $1);
				}
		)
	;

start
nullable
enum_const_list
	:	enum_const catch(enum_const_sync) (',' enum_const)*
	;

nullable
enum_const
	:	attribute_block?
		TokenKind_Identifier $n ('=' expression_pass1 $i)?
			{
				return createEnumConst($n.m_data.m_string, $n.m_pos, &$i ? &$i.m_tokenList : NULL) != NULL;
			}
	|	epsilon
	;

enum_const_sync
	:	','
	|	'}'
	;
```

**Comment by vovkos** [comment]
Apologies for not answering this earlier.

Graco-generated LL(k) parsers can use the `any` token as a convenient tool for multi-pass parsing. This approach allows describing sequences of tokens to collect for lazy-parsing later -- when (and if) needed.

`any` matches any token, but if there is a conflict of grammar productions, a production induced by `any` loses to productions caused by a specific token.  In `expression_pass1`, `any`-induced productions (that collect tokens to a token list) will lose to any production that terminates `expression_pass1` -- such as `,` in `enum_const_list` (i.e., `,` is part of the "FOLLOW"-set for `expression_pass1`).

A note worth mentioning is that `,` (or any other token from the "FOLLOW"-set of `expression_pass1`) inside sub-expressions, such as a function call with multiple arguments, won't cause termination of `expression_pass1`. That's because `expression_pass1` correctly "counts" all kinds of braces (`()`, `{}`, `[]`) inside `expression_pass1_item`.  So inside parentheses `,` won't be a part of the "FOLLOW"-set and hence, won't "compete" with `any` for the grammar production.

Hope this explains the matter.
